/*
 *  @file  : SplitQQTaskbarAddin.cpp
 *  @author: shilyx
 *  @date  : 2023-07-14 10:02:22.118
 *  @note  : Generated by SlxTemplates build:20230411
 */

#include "SplitQQTaskbarAddin.h"
#include <Windows.h>

HINSTANCE g_hinstDll = NULL;

int APIENTRY DllMain(HINSTANCE hinstDll, DWORD dwReason, LPVOID lpReserved) {
    if (dwReason == DLL_PROCESS_ATTACH) {
        g_hinstDll = hinstDll;
        // DisableThreadLibraryCalls(hinstDll);
    } else if (dwReason == DLL_PROCESS_DETACH) {

    } else if (dwReason == DLL_THREAD_ATTACH) {

    } else if (dwReason == DLL_THREAD_DETACH) {

    } else {
        // we should not be here
    }

    return TRUE;
}

void WINAPI T(HWND hwndStub, HINSTANCE hInstance, LPCSTR lpCmdLine, int nShowCmd) {
    MessageBoxA(hwndStub, lpCmdLine, "rundll32", MB_ICONINFORMATION | MB_TOPMOST);
}