/*
 *  @file  : SplitQQTaskbarAddin.h
 *  @author: shilyx
 *  @date  : 2023-07-14 10:02:22.118
 *  @note  : Generated by SlxTemplates build:20230411
 */

#ifndef _SPLITQQTASKBARADDIN_H
#define _SPLITQQTASKBARADDIN_H

#ifdef _MSC_VER
    #ifdef SPLITQQTASKBARADDIN_STATIC
        #define SPLITQQTASKBARADDIN_API
    #else
        #ifdef SPLITQQTASKBARADDIN_EXPORTS
            #define SPLITQQTASKBARADDIN_API __declspec(dllexport)
        #else
            #define SPLITQQTASKBARADDIN_API __declspec(dllimport)
        #endif
    #endif
#else
    #define SPLITQQTASKBARADDIN_API
#endif

#endif /* _SPLITQQTASKBARADDIN_H */